name: Compilar APK con Buildozer (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    # Contenedor oficial de Kivy
    container:
      image: kivy/buildozer:latest

    steps:
    - name: Copiar código del repositorio
      uses: actions/checkout@v4

    - name: Corregir permisos de Git
      run: git config --global --safe.directory /__w/kamila/kamila

    - name: Compilar APK con Buildozer
      run: |
        buildozer -v android debug

    - name: Guardar el APK generado
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: Kamila-AI-APK
        path: bin/*.apk
        
